version: '3.9'

services:
  reader-backend:
    container_name: reader-backend
    # depends_on:
    #   - reader-backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - USER_NAME=demouser
      - USER_PASSWORD=demouser
      - BOOK_DIR=/books
      - DB_HOST=reader-db
      - DB_PORT=27018
    ports:
      - "5500:5500"
    volumes:
      - ~/Documents/Books:/books:ro


  reader-db:
    image: mongo
    container_name: reader-db
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./mongo/prod:/data/db
      # - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  reader-frontend:
    container_name: reader-frontend
    # depends_on:
    #  - reader-backend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND=http://192.168.0.102:5500/
    ports:
      - 6600:80
    environment:
      NODE_ENV: production





