version: '3.9'

services:
  mongo:
    image: mongo
    container_name: test-reader-db
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./data/test:/data/db
      # - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  test-reader-mongo-express:
    image: mongo-express
    container_name: test-reader-mongo-express
    depends_on:
      # - test-reader-db 
      - mongo
    restart: unless-stopped
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@test-reader-db:27017/
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin 
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo




